### ISSUE TITLE
O docker-compose apresenta erro

### ISSUE THREAD

**Issue by patrickramosruas** [hatanakadaniel/ecommerce-checkout-api#1]
Daniel, boa noite

Tentei rodar o comando sugerido (docker-compose UP --build) mas ele está apresentando erro ao "[docker_jenkins 2/3]copy jdks/ /opt/Java/ .
Consegue me ajudar com esta falha ? Já tentei muita coisa aqui em dois SO (Ubuntu 20.04 e Windows 10 20h2)

**Comment by hatanakadaniel** [comment]
Vou ajustar o arquivo de docker-compose para você conseguir fazer o build.

**Comment by hatanakadaniel** [comment]
ajustei o arquivo `docker-compose.yml`.
